#!/bin/sh
# husky

# Created by Husky v4.3.4 (https://github.com/typicode/husky#readme)
#   At: 12/6/2020, 6:51:07 AM
#   From: undefined (https://github.com/typicode/husky#readme)

. "$(dirname "$0")/husky.sh"
